name: Build, Push and Deploy CoinForge

on:
  push:
    branches:
      - final
  workflow_dispatch:

jobs:
  # Job to set up the environment and increment the version
  setup:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.set_version.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Increment version
        id: set_version
        run: |
          # Extract the current version from a VERSION file or default to 0.1.0
          if [ -f VERSION ]; then
            version=$(cat VERSION)
          else
            version="0.5.0"
          fi

          # Increment the patch version
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))
          new_version="$major.$minor.$patch"

          # Save the new version
          echo "$new_version" > VERSION
          echo "new_version=$new_version" >> $GITHUB_ENV
          echo "::set-output name=new_version::$new_version"

      - name: Commit updated version
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add VERSION
          git commit -m "Increment version to ${{ env.new_version }}"
          git push https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}

  # Job to build and push the operator image
  build:
    needs: setup
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      new_version: ${{ needs.setup.outputs.new_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Install dependencies
        run: |
          npm install
    
      - name: Deploy contracts to Hardhat
        run: |
          CONTRACT_ID=`npx hardhat ignition deploy ignition/modules/Factory.js --network remote | grep FactoryModule | grep -o "0x[0-9a-fA-F]*"`
          echo $CONTRACT_ID
          sed -i "s/CONTRACT_ID/$CONTRACT_ID/g" app/config.json
          cat app/config.json
    
    
      - name: Get ABI file and use jq to extract the ABI
        run: |
          cat  artifacts/contracts/Factory.sol/Factory.json  | jq -r .abi > app/abis/Factory.json

      - name: Build and push Docker image for Coinforge Frontend
        run: |
          docker build  -t ${{ secrets.DOCKER_USERNAME }}/coinforge:${{ env.new_version }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/coinforge:${{ env.new_version }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/coinforge:${{ env.new_version }} ${{ secrets.DOCKER_USERNAME }}/coinforge:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/coinforge:latest

  deploy-and-release:
    needs: [build, setup]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      new_version: ${{ needs.setup.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Deploy to Kubernetes and Package YAMLs for Release
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $(pwd)/kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig

          kubectl delete deployment coinforge --ignore-not-found
          kubectl create deployment coinforge --image=${{ secrets.DOCKER_USERNAME }}/coinforge:${{ env.new_version }} --port=3000
          kubectl expose deployment coinforge --type=LoadBalancer --name=coinforge-service --port=3000 || true